### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jlopp** [decentralized-identity/sidetree-ipfs#42]
Following the instructions at https://github.com/decentralized-identity/ion and "npm i" fails with:

```
> @decentralized-identity/sidetree-ipfs@0.1.2 build /home/ion/sidetree-ipfs
> tsc -p .

/home/ion/sidetree-ipfs/node_modules/pull-stream-to-async-iterator/index.js:4
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Module.replacementCompile (/home/ion/sidetree-ipfs/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.<anonymous> (/home/ion/sidetree-ipfs/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @decentralized-identity/sidetree-ipfs@0.1.2 testCoverage: `npm run build && nyc jasmine --config=./tests/jasmine-cc.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @decentralized-identity/sidetree-ipfs@0.1.2 testCoverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by csuwildcat** [comment]
At first glance, this looks like it is probably related to running on a version of Node that lacks default support for async/iterators (v9 is currently what Bitcore requires, so the guide specifies that version). If so, this may mean you need to run Node with the `--harmony_async_iteration` flag.

Adding @thehenrytsai and @sylar217 to get their opinion.

**Comment by jlopp** [comment]
```
$ node --version
v9.11.2
```
I tried passing the flag to npm but it appears to have no effect. Also tried setting in in the NODE_OPTIONS env var but got:

```
$ npm install
node: --harmony_async_iteration is not allowed in NODE_OPTIONS
```

**Comment by csuwildcat** [comment]
@sylar217  any idea what could be causeing this?

**Comment by thehenrytsai** [comment]
Looked into this, sidetree-ipfs need node version 10+ for this. We should and will add that in the documentation.
Easiest thing to do is to use `nvm` to install Node v10+ if you have to keep node 9 also:

`nvm install 10.15.3`

**Comment by jlopp** [comment]
Thanks, that fixed the issue with npm install. Now I'm getting an error trying to run the service:

```
$ npm run build

> @decentralized-identity/sidetree-ipfs@0.1.2 build /home/ion/sidetree-ipfs
> tsc -p .

$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ion/.npm/_logs/2019-04-26T17_59_26_384Z-debug.log

```

Here's the debug log:

```
1 verbose cli [ '/home/ion/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/home/ion/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose stack Error: missing script: start
4 verbose stack     at run (/home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /home/ion/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/ion/sidetree-ipfs
6 verbose Linux 4.15.0-1035-aws
7 verbose argv "/home/ion/.nvm/versions/node/v10.15.3/bin/node" "/home/ion/.nvm/versions/node/v10.15.3/bin/npm" "start"
8 verbose node v10.15.3
9 verbose npm  v6.4.1
10 error missing script: start
11 verbose exit [ 1, true ]
```

**Comment by thehenrytsai** [comment]
Sorry for the late reply. This repo is deprecated and the code now lives directly in Sidetree repo.

Use `npm run ipfs` to run the microservice.
